# Generated by Django 6.0.3 on 2026-05-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='cast',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
