# Generated by Django 4.2.30 on 2026-05-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movievideo',
            name='dood_file_code',
            field=models.CharField(help_text='DoodStream File Code', max_length=100),
        ),
    ]
