# Generated by Django 4.2.30 on 2026-05-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movievideo_dood_file_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movievideo',
            name='thumbnail_url',
        ),
        migrations.AlterField(
            model_name='movievideo',
            name='dood_file_code',
            field=models.CharField(help_text='DoodStream File Code (ဥပမာ - y1kr94f8in6y)', max_length=100),
        ),
        migrations.AlterField(
            model_name='movievideo',
            name='duration',
            field=models.CharField(blank=True, help_text='ဥပမာ - 1h 52m', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movievideo',
            name='file_size',
            field=models.CharField(blank=True, help_text='ဥပမာ - 1.2 GB', max_length=100, null=True),
        ),
    ]
