# Generated by Django 6.0.3 on 2026-05-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cast_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='director',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='premiere',
            name='year',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, unique=True),
        ),
    ]
