# Generated by Django 6.0.3 on 2026-05-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_director_director_alter_premiere_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
