# Generated by Django 6.0.3 on 2026-05-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_herosection_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='telegram_file_id',
        ),
    ]
