# Generated by Django 6.0.3 on 2026-05-11 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_movie_telegram_file_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-created_at'], 'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='series',
            name='casts',
            field=models.ManyToManyField(related_name='series_list', to='api.cast'),
        ),
        migrations.AlterField(
            model_name='series',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_list', to='api.country'),
        ),
        migrations.AlterField(
            model_name='series',
            name='directors',
            field=models.ManyToManyField(related_name='series_list', to='api.director'),
        ),
        migrations.AlterField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(related_name='series_list', to='api.genre'),
        ),
        migrations.AlterField(
            model_name='series',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_list', to='api.rating'),
        ),
        migrations.AlterField(
            model_name='series',
            name='release_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_list', to='api.premiere'),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True),
        ),
    ]
