# Generated by Django 6.0.3 on 2026-05-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_season_episode_series_season_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='video_file',
        ),
        migrations.AddField(
            model_name='episode',
            name='dood_file_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='file_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
