# Generated by Django 6.0.3 on 2026-05-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_shops', 'Can create and manage shops'), ('can_access_premium_content', 'Can access premium video content')]},
        ),
    ]
